name: Build Latest

on:
  release:
    types: [created]

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ github.event.repository.name }}
          tags: latest
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
